name: Check Changelog and Version

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    env:
      CI_MERGE_REQUEST_SOURCE_BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
      CI_MERGE_REQUEST_TARGET_BRANCH_NAME: ${{ github.event.pull_request.base.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --force
      - uses: flotiq/check-changelog-and-version@v0.1.2
        with:
          changelog_file: CHANGELOG.md
          version_file: package.json